package co.gov.banrep.iconecta.cs.documento.utils;

public enum NombreServicio {
	GET_NODE,
	UPDATE_NODE,
	PURGE_VERSIONS,
	GET_VERSIONS_CONTENTS,
	GET_NODE_BY_NAME,
	COPY_NODE,
	UPDATE_NODE_RIGHT,
	ADD_VERSION,
	RENAME_NODE,
	CREATE_DOCUMENT,
	GET_CATEGORY_TEMPLATE,
	MOVE_NODE,
	DELETE_NODE,
	GET_NODES_IN_CONTAINER,
	RUN_REPORT
}
