package co.gov.banrep.iconecta.ssm.firma.enums;

public enum Events {
	INICIAR, DOCUMENTO_OBTENIDO_CS, CIRCUITO_INICIADO,
	ERROR_OPERACION, RESPUESTA_PF_EXITOSA, RESPUESTA_PF_CANCELADO,
	INICIAR_FASE_FINAL, DOCUMENTO_FIRMADO, DOCUMENTO_ACTUALIZADO, 
	DOCUMENTO_ACTUALIZADO_COPIA_COMPULSADA, COPIA_COMPULSADA_OBTENIDA, 
	COPIA_COMPULSADA_ACTUALIZADA, WORKFLOW_INICIADO, ERROR_OPERACION_FINAL, ERROR_OPERACION_FINAL_SIN_REINTENTO,
	NUMERO_MAXIMO_REINTENTOS_ALCANZADO, FINALIZAR_CANCELACION, ACCION_EXTERNA_FINALIZADA, FINALIZAR_CANCELACION_ALTERNATIVA
	
}
