package co.gov.banrep.iconecta.ssm.firma.enums;

public enum States {
	FASE_INICIAL, LISTO, INICIALIZAR_PARAMETROS, OBTENER_DOCUMENTO_CS, INICIAR_CIRCUITO_PF, INICIAR_WF_NOTIFICACION, ESPERANDO_RESPUESTA_PF, FASE_FINAL, LISTO_FASE_FINAL, OBTENER_DOCUMENTO_PF, ACTUALIZAR_DOC_CS, OBTENER_COPIA_COMPULSADA_PF, CARGAR_COPIA_COMPULSADA_CS, INICIAR_WF_NOTIFICACION_FINAL, ESPERARNDO_REINENTO, HISTORY, FINALIZADO, FINALIZADO_ERRORES, FINALIZADO_CANCELADO, INICIAR_TAREA_CANCELACION, FINALIZADO_CANCELADO_ALTERNATIVO, INICIAR_TAREA_FINAL, ACCION_FINAL_ALTERNATIVA, FINALIZADO_CORRECTO, FIN_FASE_INICIAL, FINALIZADO_ERRORES_NORMAL, FINALIZADO_ERRORES_ALTERNATIVO
}
