package co.gov.banrep.iconecta.ssm.correspondencia.enums;

public enum Events {
	
	
	//--------------------------------------------------------------------------------------
	//-----------------                     DER                    -------------------------
	INICIAR_RADICAR_DER,
	IR_INICIAR_WF_FORMULARIO_DER_REMOTO, 
	IR_ESPERAR_OBTENER_DATOS_CATEGORIA_FORM_DER, 
	IR_OBTENER_DATOS_CATEGORIA_FORM_DER,
	IR_CARGAR_CATEGORIA_FORMULARIO_DER,
	VOLVER_CARGAR_CATEGORIA_FORMULARIO_DER, //PARA REINTENTOS
	IR_VALIDAR_FORMA_ENTREGA_DER,
	IR_ESPERAR_DIGITALIZAR_DER,
	IR_CARGAR_CATEGORIA_DOC_DIGITALIZADO_DER,
	VOLVER_CARGAR_CATEGORIA_DOC_DIGITALIZADO_DER, //PARA REINTENTOS
	IR_ESPERAR_CALIDAD_DIGITALIZAR_DER,	
	IR_DISTRIBUIR_DER, 
	VOLVER_DISTRIBUIR_DER, //PARA REINTENTOS
	IR_ESPERAR_RESULTADO_DISTRIBUIR_DER, 
	IR_ACTUALIZAR_ESTADO_FINAL_CORR_DER,
	FINALIZAR_DER, 
	//--------------------------------------------------------------------------------------
	
	
	
	
	//--------------------------------------------------------------------------------------
	//-----------------                     DER-EMAIL                    -------------------------
	INICIAR_RADICAR_DER_EMAIL,
	IR_CARGAR_CATEGORIA_CORREO_DER, 
	VOLVER_CARGAR_CATEGORIA_CORREO_DER, //PARA REINTENTOS
	//IR_DISTRIBUIR_DER, 
	//VOLVER_DISTRIBUIR_DER, //PARA REINTENTOS
	//IR_ESPERAR_RESULTADO_DISTRIBUIR_DER, 
	//IR_ACTUALIZAR_ESTADO_FINAL_CORR_DER,
	//FINALIZAR_DER, 
	//--------------------------------------------------------------------------------------
	
	
	
	
	
	//--------------------------------------------------------------------------------------
	//-----------------                     CARTA/MEMO                    -------------------------
	INICIAR_RADICAR_CA_ME,
	IR_CARGAR_METADATOS_PLANTILLA_CA_ME,
	IR_ACTUALIZAR_RADICADO_DOC_CA_ME,
	IR_RENOMBRAR_DOC_CS_CA_ME,
	IR_GENERAR_DOCS_PERSONALIZADOS_CARTA,
	IR_SUBIR_DOCS_PERSONALIZADOS_CS_CARTA,
	IR_CONVERTIR_UNIR_PDF_CA_ME,	
	IR_ESPERAR_PROCESO_CA_ME,
	IR_CARGAR_CAT_CORR_CS_CA_ME,
	IR_ENVIAR_FIRMA_CA_ME,
	IR_ESPERAR_RESULTADO_FIRMA_CA_ME,
	IR_EVALUAR_RESULTADO_FIRMA_CA_ME,
	
	IR_DISTRIBUIR_MEMORANDO, 
	IR_DISTRIBUIR_CARTA,
	//--------------------------------------------------------------------------------------
	
	//--------------------------------------------------------------------------------------
	//-----------------                     UTILITARIOS                    -------------------------
	IR_FINALIZADO_ERRORES, 
	IR_FINALIZADO_ERRORES_FUNCIONALES,
	ERROR_REINTENTO, 
	//--------------------------------------------------------------------------------------
	
	
	
	
	
	
	
	DOCUMENTO_OBTENIDO_CS,
	FINALIZAR, 
	FIRMA_FINALIZADO_OK, 
	DISTRIBUCION_FINALIZADA, 
	VOLVER_ESPERAR_DISTRIBUIR, 
	FIRMA_CANCELADA, 
	NUM_RADICADO_OBTENIDO, 
	INICIAR_RADICAR_RDI_RDE, 
	FINALIZAR_RDI_RDE, 
	VOLVER_ESPERAR_DISTRIBUIR_RDI_RDE, 
	OBTENIENDO_RESULTADO_DISTRIBUIR_RDI_RDE, 
	INICIAR_CARGAR_CATEGORIA_RDI_RDE, 
	IR_OBTENER_RESPUESTA_DISTRIBUIR_CDD_RDI_RDE, 
	IR_ESPERAR_RESPUESTA_DISTRIBUIR_CDD_RDI_RDE, 
	IR_ESPERAR_RESPUESTA_DISTRIBUIR_RDI_RDE, 
	FIRMA_FINALIZADO_OK_CARTA, 
	IR_OBTENER_RESPUESTA_DISTRIBUIR_CDD_CARTA, 
	IR_ESPERAR_RESPUESTA_DISTRIBUIR_CDD_CARTA, 
	IR_ESPERAR_FIRMA, 
	IR_ESPERAR_RESPUESTA_DISTRIBUIR_CARTA, 
	IR_OBTENER_RESPUESTA_DISTRIBUIR_CARTA, 
	IR_SUBIR_DOC_CONSECUTIVO, 
	VOLVER_ESPERAR_DISTRIBUIR_CARTA, 
	 
	 
	
	
	 
	//IR_OBTENER_RESPUESTA_DISTRIBUIR_DER, 
	VOLVER_ESPERAR_DISTRIBUIR_DER, 
	
	ERROR_OPERACION_FINAL_SIN_REINTENTO,
	NUMERO_MAXIMO_REINTENTOS_ALCANZADO, 
	WORKFLOW_INICIADO, 
	
	IR_INTENTAR, 
	IR_INTENTAR_DISTRIBUIR, 
	IR_INTENTAR_OBTENER_RESULTADO_DISTRIBUIR, 
	IR_VALIDAR_INICIAR_FORMA_DISTRIBUIR_RDI_RDE, 
	VOLVER_OBTENER_RESPUESTA_DISTRIBUIR_CDD_RDI_RDE, 
	VOLVER_OBTENIENDO_RESULTADO_DISTRIBUIR_RDI_RDE, 
	IR_REASIGNAR_RUTA_DER, 
	IR_GENERAR_RADICADO_CORREO, 
	 
	 
	//VOLVER_REASIGNAR_RUTA_DER, 
	VOLVER_DISTRIBUIR_CARTA, 
	VOLVER_OBTENER_RESPUESTA_DISTRIBUIR_CDD_CARTA, 
	VOLVER_OBTENER_RESPUESTA_DISTRIBUIR_CARTA, 
	IR_VALIDAR_INICIAR_FORMA_DISTRIBUIR_RDI_RDE_REINTENTO, 
	
	IR_VERIFICAR_VERSION_PLANTILLA, IR_GENERAR_STICKER_CARTA
	
	
	
	
	 
	 
	
	 
	

}
