package co.gov.banrep.iconecta.ssm.correspondencia.enums;

public enum States {
	//ESTADO PADRE, INICIO IGUAL PARA TODAS LAS TIPOLOGÍAS
	INICIO, 
	
	//--------------------------------------------------------------------------------------
	//-----------------                     DER                    -------------------------
	INICIO_RADICAR_DER, 
	INICIAR_WF_GENERAR_NUM_RADICADO_DER, 
	INICIAR_WF_FORMULARIO_DER_REMOTO, 
	ESPERAR_OBTENER_DATOS_CATEGORIA_FORM_DER,
	OBTENER_DATOS_CATEGORIA_FORM_DER, 
	CARGAR_CATEGORIA_FORMULARIO_DER, 
	VALIDAR_FORMA_ENTREGA_DER, 
	ESPERAR_DIGITALIZAR_DER,
	CARGAR_CATEGORIA_DOC_DIGITALIZADO_DER,
	ESPERAR_CALIDAD_DIGITALIZAR_DER, 	
	SUBIR_DOC_CONSECUTIVO_DER, 
	DISTRIBUIR_DER, 
	ESPERAR_RESULTADO_DISTRIBUIR_DER,
	ACTUALIZAR_ESTADO_FINAL_CORR_DER,
	FIN_DER,
	//--------------------------------------------------------------------------------------
	
	
	
	
	
	//--------------------------------------------------------------------------------------
	//-----------------                     DER-EMAIL                   -------------------------
	INICIO_RADICAR_DER_EMAIL, 
	//INICIAR_WF_GENERAR_NUM_RADICADO_DER, 
	CARGAR_CATEGORIA_CORREO_DER,
	//7SUBIR_DOC_CONSECUTIVO_DER, 
	//DISTRIBUIR_DER, 
	//ESPERAR_RESULTADO_DISTRIBUIR_DER,
	//ACTUALIZAR_ESTADO_FINAL_CORR_DER,
	//FIN_DER,	
	//--------------------------------------------------------------------------------------
	
	
	//--------------------------------------------------------------------------------------
	//-----------------                     CARTA/MEMO                    -------------------------
	CARGAR_PROPS_INICIALES_CA_ME, 
	OBTENER_METADATOS_PLANTILLA_CA_ME,
	CARGAR_METADATOS_PLANTILLA_CA_ME,
	INICIAR_WF_GENERAR_NUM_RADICADO_CA_ME, 
	ACTUALIZAR_RADICADO_DOC_CA_ME,
	RENOMBRAR_DOC_CS_CA_ME,
	GENERAR_DOCS_PERSONALIZADOS_CARTA,
	SUBIR_DOCS_PERSONALIZADOS_CS_CARTA,
	CONVERTIR_UNIR_PDF_CA_ME,
	ESPERAR_PROCESO_CA_ME,
	CONSULTAR_CONVERTIR_UNIR_PDF_CA_ME,
	CARGAR_CAT_CORR_CS_CA_ME,
	ENVIAR_FIRMA_CA_ME,
	ESPERAR_RESULTADO_FIRMA_CA_ME,
	EVALUAR_RESULTADO_FIRMA_CA_ME,
	
	DISTRIBUIR_CARTA, 
	DISTRIBUIR_MEMORANDO, 
	//DISTRIBUIR_MEMORANDO_E,
	//--------------------------------------------------------------------------------------
	
	
	
	
	//--------------------------------------------------------------------------------------
	//-----------------                     UTILITARIOS                    -------------------------
	ESPERANDO_REINTENTO,
	FINALIZADO_ERRORES_FUNCIONALES, 
	FINALIZADO_ERRORES,  
	VERIFICAR_REINTENTO,
	//--------------------------------------------------------------------------------------
	
	
	OBTENER_DOCUMENTO_CS,
	VERIFICAR_VERSION_PLANTILLA_DOC,
	
	CARGAR_CATEGORIA_CS,
	
	
	CARGAR_NUEVA_VERSION_DOC_CS,
	
	FIN,  
	ESPERAR_FIRMA,

	ESPERAR_RESULTADO_DISTRIBUIR, 
	OBTENER_RESULTADO_DISTRIBUIR, 
	FIRMA_CANCELADA_ANULAR_DOC,
	
	INICIO_RADICAR_RDI_RDE, 
	INICIAR_WF_GENERAR_NUM_RADICADO_RDI_RDE, 
	CARGAR_CATEGORIA_CS_RDI_RDE, 
	DISTRIBUIR_RDI_RDE, 
	ESPERAR_RESULTADO_DISTRIBUIR_RDI_RDE, 
	FIN_RDI_RDE, 
	OBTENER_RESULTADO_DISTRIBUIR_RDI_RDE,  
	OBTENER_DATOS_CATEGORIA_FORM_RDI_RDE, 
	VALIDAR_INICIAR_FORMA_DISTRIBUIR_RDI_RDE, 
	ESPERAR_RESPUESTA_DISTRIBUIR_CDD_RDI_RDE, 
	OBTENER_RESPUESTA_DISTRIBUIR_CDD_RDI_RDE, 
	GENERAR_STICKER_RDI_RDE, 
	VERIFICAR_WF_CONFIDENCIAL, 
	VERIFICAR_ANEXOS, 
	GENERAR_DOCUMENTO_FORMULARIO_RDI_RDE, 
	
	 
	
	GENERAR_STICKER_CARTA, 
	ESPERAR_RESPUESTA_DISTRIBUIR_CDD_CARTA, 
	OBTENER_RESPUESTA_DISTRIBUIR_CDD_CARTA, 
	ESPERAR_RESPUESTA_DISTRIBUIR_CARTA, 
	OBTENER_RESPUESTA_DISTRIBUIR_CARTA, 
	SUBIR_DOC_CONSECUTIVO, 
	
	
	
	 
	
	
	//IR_DISTRIBUIR_DER, 
	 
	//IR_ESPERAR_DIGITALIZAR_DER, 
	//IR_ESPERAR_CALIDAD_DIGITALIZAR_DER, 
	
	
	 
	//OBTENER_RESULTADO_DISTRIBUIR_DER, 
	 
	 
	HISTORY, 
	 
	//OBTENER_RESULTADO_DER, 
	//REASIGNAR_RUTA_DER, 
	//INICIAR_WF_GENERAR_NUM_RADICADO_CORREO_DER, 
	
	//DISTRIBUIR_CORREO_DER, 
	
	FINALIZADO, 
	
	 
	 
	

}
